### ISSUE TITLE
Can't test later parts of tutorial in level editor

### ISSUE THREAD

**Issue by Poobslag** [Poobslag/turbofat#505]
When you try to open the later parts of the tutorial (e.g tutorial-beginner-4.json) it forces you back to the beginning of the tutorial in a weird state.

**Comment by Amavect** [comment]
This appears to be caused by the interaction of `res://src/main/puzzle/puzzle-state.gd` with the tutorial json files having a `start_level` field.
```
func _prepare_game() -> void:
	game_active = false
	finish_triggered = false
	game_ended = false
	
	if CurrentLevel.settings.other.start_level:
		# Load a different level to start (used for tutorials)
		var new_settings := LevelSettings.new()
		new_settings.load_from_resource(CurrentLevel.settings.other.start_level)
		CurrentLevel.start_level(new_settings)
	
	reset()
	emit_signal("game_prepared")
	emit_signal("after_game_prepared")
```
Not sure why the `if start_level` hook is there in the first place.
Only the tutorial levels use it, and loading `oh-my.json` throws an error because `"start_level marathon_hard"` references a file that was moved.

Maybe delete the if block?

**Comment by Amavect** [comment]
That is indeed the case.
I like that "Retry" and "Start" are the same button :)
Because of that, I almost want to call it intended behavior.

I've found some related behavior.
If I use the Open File on a tutorial level (for example, `tutorial/basic-1.json`), the id opens as `basic_1`, but if I use Open Resource, the id opens as `tutorial/basic_1`.
This is due to how `res://src/main/puzzle/level/level-settings.gd` generates the level key based on the path in `level_key_from_path()`.

This leads to the tutorial playing correctly (but with a customer that's not Turbo) if I use Open Resource, but not if I use Open File.
The string matching in `res://src/main/puzzle/tutorial/tutorial-hud.gd` in `replace_tutorial_module()` causes this.
The interaction between these two things explains the "weird state".

I'm not sure what to do about this...

**Comment by Poobslag** [comment]
Right, that's intended behavior. If you're loading a random file on your machine, not a file in the game's resources, so it obviously wouldn't make sense to set the ID to something like `Users/Amavect/My Documents/basic_1` or whatever.

It seems strange when you have the Godot project open or when you're navigating through the source code, but that's not what a typical user would be doing.

**Comment by Poobslag** [comment]
The level editor has been removed.
